<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
		<IsTestProject>true</IsTestProject>
		<LangVersion>14</LangVersion>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="FFMpegCore" Version="5.2.0" />
		<PackageReference Include="FFMpegCore.Extensions.System.Drawing.Common" Version="5.0.2" />
		<PackageReference Include="MarkdownSnippets.MsBuild" Version="27.0.2" PrivateAssets="All" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
		<PackageReference Include="Mono.Posix.NETStandard" Version="1.0.0" />
		<PackageReference Include="NSubstitute" Version="5.1.0" />
		<PackageReference Include="NUnit" Version="4.1.0" />
		<PackageReference Include="NUnit.Analyzers" Version="4.3.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
		<PackageReference Include="SharpAvi" Version="3.0.1" />
		<PackageReference Include="SharpAvi.ImageSharp" Version="3.0.0" />
		<PackageReference Include="System.Drawing.Common" Version="9.0.8" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
		<PackageReference Include="Microsoft.AspNetCore.Connections.Abstractions" Version="2.2.0" />
	</ItemGroup>
	<Import Project="../Common/CommonProps.props" />
	<ItemGroup>
		<ProjectReference Include="..\PuppeteerSharp.TestServer\PuppeteerSharp.TestServer.csproj" />
		<ProjectReferenc1e Include="..\PuppeteerSharp\PuppeteerSharp.csproj" />
		<ProjectReference Include="..\PuppeteerSharp.Nunit\PuppeteerSharp.Nunit.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Assets\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="test.runsettings">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<None Remove="xunit.runner.json" />
		<Content Include="xunit.runner.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
	  <None Remove="TestExpectations\TestExpectations.json" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="CDPSessionTests\Screencasting\samples\puppeteer\" />
	</ItemGroup>
  <PropertyGroup>
    <NoWarn>8002</NoWarn>
  </PropertyGroup>
</Project>
